### ISSUE TITLE
Lista de canciones favoritas

### ISSUE THREAD

**Issue by EuniceCalle** [EuniceCalle/My_Playlist#1]
1. Cada persona tienes que crea su branch con formato "nombre_apellido" 
2. Cada persona debe editar el archivo "Mi_Cancion.txt" agregando su canción favorita.
3. Recuerden que tienen que relacionarlo al Issue en el "Summary Required" de GitHub Desktop.

**Comment by EuniceCalle** [comment]
Hola @CesarQN ya puedes agregar tu canción

**Comment by CesarQN** [comment]
Chicos subí  mi canción!!

**Comment by EuniceCalle** [comment]
Genial Cesar!!
